# Define the Risk Map based on the assessment for wheelchair users
RISK_MAP = {
    "fire": ("High", ["Trigger fire alarm", "Evacuate area", "Call emergency services"]),
    "smoke": ("High", ["Trigger fire alarm", "Evacuate area", "Call emergency services"]),
    "wet floor": ("High", ["Alert and clean area", "Install non-slip mats", "Mark wet floor"]),
    "stairs": ("High", ["Install railing", "Mark stair edges", "Alert user"]),
    "cluttered walkways": ("High", ["Tidy up area", "Remove obstacles"]),
    "loose rugs": ("High", ["Secure rug", "Install non-slip mats"]),
    "electrical cords": ("High", ["Tidy cords", "Install cord covers"]),
    "sharp furniture": ("High", ["Cover sharp edges", "Install padded barriers"]),
    "pet in path": ("High", ["Alert caregiver", "Pause movement", "Redirect path"]),
    "narrow doorway": ("High", ["Widen doorframe", "Move obstacles"]),
    "grab bars missing": ("High", ["Install grab bars", "Ensure stability"]),
    "wheelchair near stairs": ("High", ["Move wheelchair", "Alert user"]),
    "fallen user": ("High", ["Alert emergency personnel", "Check for motion"]),
    "overheating appliance": ("High", ["Turn off appliance", "Ensure user is safe"]),
    "obstructed exit": ("High", ["Clear exit path", "Ensure accessibility"]),
    "tipped wheelchair": ("High", ["Check wheelchair condition", "Alert caregiver"]),
    "open flames": ("High", ["Turn off open flames", "Move items away"]),
    "broken floor tiles": ("High", ["Repair tiles", "Alert user"]),
    "poor lighting": ("High", ["Increase lighting", "Ensure clear paths"]),
    "inaccessible emergency button": ("High", ["Make button accessible", "Clear obstructions"]),
    "overloaded socket": ("High", ["Reduce plugs", "Ensure proper safety"]),
    "high countertops": ("Medium", ["Lower countertop", "Ensure access"]),
    "tight furniture spacing": ("Medium", ["Rearrange furniture", "Increase spacing"]),
    "narrow hallway": ("Medium", ["Widen hallway", "Rearrange furniture"]),
    "shower without seat": ("Medium", ["Install shower seat", "Ensure roll-in space"]),
    "no stair handrails": ("Medium", ["Install handrails", "Ensure stability"]),
    "manual doors": ("Medium", ["Install automatic door", "Ensure access"]),
    "high thermostats": ("Medium", ["Lower thermostat", "Ensure reach"]),
    "steep ramps": ("Medium", ["Fix ramp angle", "Ensure non-slip surface"]),
    "high objects": ("Medium", ["Lower objects", "Ensure reachability"]),
    "inaccessible storage": ("Medium", ["Reorganize storage", "Install accessible shelves"]),
    "unstabl furniture": ("Medium", ["Fix furniture", "Check stability"]),
    "slanted ramps": ("Medium", ["Fix slope", "Ensure accessibility"]),
    "tv remote unreachable": ("Low", ["Lower remote", "Ensure access"]),
    "decorative items blocking switches": ("Low", ["Rearrange decor", "Ensure switches are accessible"]),
    "inaccessible window latches": ("Low", ["Lower window latches", "Ensure access"]),
    "high wall sockets": ("Low", ["Reorganize furniture", "Ensure sockets are reachable"]),
    "inaccessible curtains": ("Low", ["Lower curtain rods", "Use automatic blinds"]),
    "unlabeled_containers": ("Low", ["Label containers", "Ensure identification"]),
    "unstable shelves": ("Low", ["Secure shelves", "Organize items"]),
    "heavy doors": ("Low", ["Install auto-close", "Assist with door"]),
    "floor object under tables": ("Low", ["Clear space under tables", "Reorganize items"]),
    "no visual markers for elevation": ("Low", ["Add contrast strips", "Mark elevation changes"]),
}
